### ISSUE TITLE
prefix displays as "unknown"

### ISSUE THREAD

**Issue by Rustypredator** [CodeCrafter47/FreeBungeeChat#7]
I have a bungeecord setup running, and am trying to get the prefix to work, but it just displays "unknown".

I have BungeePerms and FBC running on bungeecord, and on the spigot server im testing on. i also have vault on that spigot server.

are there any other requirements for working prefix support??

Thanks for the help in advance :)

**Comment by CodeCrafter47** [comment]
Prefix support is broken in BungeePerms unless you use the latest dev-build.

**Comment by Rustypredator** [comment]
uh, the latest dev build was like 4 months ago, right?
because, if i just run one spigot server with the versuion of bungeePerms and essentialschat on, i can see the prefixes.

Edit: actually, the latest dev seems to be the latest release... so i cant get a newer version? (http://ci.wea-ondara.net/job/BungeePerms/lastBuild/net.alpenblock$BungeePerms/)

**Comment by Rustypredator** [comment]
Update: Well, i tried that version anyways... now FBC doesnt display unknown but [B] ??
is that some default prefix or something? i have deactivated essentials btw. i checked, and 

```
/bp user Rustypredator info
```

gives no prefix, but

```
/bp group admin info
```

says the group has a prefix (im member of that group...)

also, if i give my player an individual prefix it still only displays [B] as prefix

**Comment by CodeCrafter47** [comment]
There is no such thing as a default prefix. If it shows [B] as prefix then because you configured that. Normally BungeePerms should show all prefixes you set for a user (it will put the per user and per group prefixes just after each other), but if you change the prefixes with the command and you don't see an immediate effect you might need to restart your server. If in doubt looking at the database or yml file can help finding issues.

**Comment by Rustypredator** [comment]
meh, i surely dont have set it to [B] :D 
I'll take a look at the yml

**Comment by Rustypredator** [comment]
config.yml:

```
useUUIDs: false
useregexperms: false
grouppermission: true
backendtype: YAML
uuidplayerdb: none
tablePrefix: bungeeperms_
uuidfetcher:
  cooldown: 3000
saveAllUsers: true
deleteUsersOnCleanup: false
notify:
  promote: false
  demote: false
tabcomplete: false
locale: en-GB
networktype: Global
networkservers: []
debug:
  path: /home/bungee/bungeecord/plugins/BungeePerms/debug.log
  showexceptions: true
  showlogs: false
terminate:
  prefix:
    reset: true
    space: true
  suffix:
    reset: true
    space: true
cleanup:
  interval: 1800
  threshold: 600
```

permissions.yml

```
groups:
  Admin:
    rank: 1
    default: false
    display: '&4[Admin]'
    prefix: '&3<&2TEAM&3||&4ADMIN&3>>&f'
    suffix: ''
    inheritances: []
    permissions:
    - '*'
    - bungeeperms.*
    - bungeetablistplus.*
    - bungeecord.command.*
    weight: 1000
    ladder: default
  newbie:
    inheritances: []
    permissions:
    - bungeecord.command.server
    - bungeecord.command.list
    - bungeeportals.portal.*
    - essentials.spawn
    rank: 1000
    ladder: default
    default: true
    display: ''
    prefix: ''
    suffix: ''
    weight: 1000
version: 1
users:
  Rustypredator:
    groups:
    - Admin
    permissions: []
    display: ''
    prefix: ''
    suffix: ''
```

Sorry if i bug you with that, but the developer of bp does not seem to care, and you seem to be very active there so...

I cant seem to find any errors there... also i removed the display of admin group, but still no effect
